apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash,check_password_hash
import enum
from datetime import datetime


"""
(my_env) $ pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple shortuuid
"""


# pip install shortuuid

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4

class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100),primary_key=True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11),nullable=False,unique=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50),unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)

    def __init__(self,*args,**kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser, self).__init__(*args,**kwargs)


    @property
    def password(self):
        return self._password

    @password.setter
    def password(self,newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self,rawpwd):
        return check_password_hash(self._password,rawpwd)

apps/front/forms.py
from apps.forms import BaseForm
from wtforms import StringField,IntegerField
from wtforms.validators import regexp,InputRequired,EqualTo,ValidationError,Regexp
import hashlib
from utils import zlcache



class SMSCaptchaForm(BaseForm):
    salt = 'q3423805gdflvbdfvhsdoa`#$%'#盐是随便给的
    telephone = StringField(validators=[regexp(r'1[345789]\d{9}')])
    timestamp = StringField(validators=[regexp(r'\d{13}')])
    sign = StringField(validators=[InputRequired()])#Md5值

    def validate(self):
        result = super(SMSCaptchaForm, self).validate()
        if not result:
            return False

        telephone = self.telephone.data
        timestamp = self.timestamp.data
        sign = self.sign.data

        # md5(timestamp+telphone+salt)
        # md5函数必须要传一个bytes类型的字符串进去
        sign2 = hashlib.md5((timestamp + telephone + self.salt).encode('utf-8')).hexdigest()
        print('客户端提交的sign：', sign)
        print('服务器生成的sign：', sign2)
        if sign == sign2:
            return True
        else:
            return False


"""
这上边全是
158讲讲的
下边是161讲
"""
class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}",message='请输入正确格式的手机号码！')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码！')])
    username = StringField(validators=[Regexp(r".{2,20}",message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}",message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1",message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码！')])

    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data
        #
        # sms_captcha_mem = zlcache.get(telephone)
        # if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
        #     raise ValidationError(message='短信验证码错误！')
        if sms_captcha != '1111':
            sms_captcha_mem = zlcache.get(telephone)
            if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
                raise ValidationError(message='短信验证码错误！')


    def validate_graph_captcha(self,field):
        graph_captcha = field.data

        # graph_captcha_mem = zlcache.get(graph_captcha.lower())
        # if not graph_captcha_mem:
        #     raise ValidationError(message='图形验证码错误！')
        if graph_captcha != '1111':#这是自己写的测试代码,上面也是,这里这么写是因为真正的注册需要一个真正的手机号码来注册，比较麻烦
            graph_captcha_mem = zlcache.get(graph_captcha.lower())
            if not graph_captcha_mem:
                raise ValidationError(message='图形验证码错误！')

class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remeber = StringField()




class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])

apps/common/views.py
from flask import  Blueprint,jsonify
import qiniu

bp = Blueprint("common",__name__,url_prefix='/common')

@bp.route('/')
def index():
    return 'common  index'



# @app.route('/uptoken/')
@bp.route('/uptoken/')
def uptoken():#这个需要自己申请一个
    access_key = '6C0-gZV-pWuDoRiRU1tq14P5gW1wFbq0GEtq_zeP'
    secret_key = 'AgPOGPd3MLamYt4U-5rhl8LRcxRxEf_ljrotu0Gn'
    q = qiniu.Auth(access_key,secret_key)

    bucket = 'richard1230'#存储空间名字
    token = q.upload_token(bucket)
    return jsonify({'uptoken':token})

apps/front/__init__.py
from .views import bp
from . import hooks


"""
只要引用了front这个文件,就会执行这个__init__.py代码
就会执行hooks里面的代码
"""

apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    make_response,
    Response,
    Flask,
    request,
session,
url_for,
g,abort

)
from utils.captcha import Captcha
from io import BytesIO
from PIL import Image, ImageFont, ImageDraw
from utils.CCPSDK import CCPRestSDK
from utils import restful,zlcache,safeutils
import config
from .forms import SMSCaptchaForm,SignupForm,SigninForm,AddPostForm,AddCommentForm
from .models import FrontUser
from  ..models import BannerModel,BoardModel,PostModel,CommentModel,HighlightPostModel
from .decorators import login_required
from flask_paginate import  Pagination,get_page_parameter

from exts import db
import config
from sqlalchemy.sql import func
from tasks import send_sms_captcha

bp = Blueprint("front", __name__)  # url_prefix='cms'表示一个前缀,这里不需要


@bp.route('/')
def index():
    board_id = request.args.get('bd',type=int,default=None)
    page = request.args.get(get_page_parameter(),type=int,default=1)
    sort = request.args.get("st",type=int,default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    # posts= PostModel.query.all()
    #开始位置和结束位置
    start =(page-1)*config.PER_PAGE
    end = start +config.PER_PAGE
    pasts = None
    total = 0

    query_obj=None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:
        query_obj =query_obj.filter(PostModel.board_id==board_id)
        posts = query_obj.slice(start,end)
        total = query_obj.count()
    else:
        posts=query_obj.slice(start,end)
        total = query_obj.count()

    #bs_version表示bootstrap的版本号
    pagination = Pagination(bs_version=3, page=page,total=total,outer_window=0,inner_window=2)
    context = {
        'banners': banners,
        'boards': boards,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort
    }

    return render_template('front/front_index.html',**context)


@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html',post=post)


#添加帖子评论
@bp.route('/acomment/',methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这篇帖子！')
    else:
        return restful.params_error(form.get_error())




#添加帖子
@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:#这里是post方法,需要表单
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title,content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())



@bp.route('/test/')
def front_test():
    return render_template('front/front_test.html')


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    #存储图形验证码到服务器
    zlcache.set(text.lower(),text.lower())

    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    # print(resp)
    # resp = Response(resp,mimetype="image/png")
    # resp.context_type = 'image/png'
    resp.headers['Content-Type'] = 'image/jpg'

    return resp

# @bp.route('/sms_captcha/')
# def sms_captcha():
#     telephone=request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message='请传入手机号码')
#     accountSid = "8a216da86f17653b016f3b4046b218ab"
#     accountToken = "ac156972012a43dab1782f1f89995ac9"
#     appId = "8a216da86f17653b016f3b40471818b2"
#     rest = CCPRestSDK.REST(accountSid, accountToken, appId)
#     #下面要有产生随机的验证码函数
#     captcha= Captcha.gene_text(number=4)
#     result = rest.sendTemplateSMS(telephone, [captcha], "1")
#     if result:
#         return restful.success()
#     else:
#         return restful.params_error(message='短信验证码发送失败')

@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone=form.telephone.data

        accountSid = "8a216da86f17653b016f3b4046b218ab"
        accountToken = "ac156972012a43dab1782f1f89995ac9"
        appId = "8a216da86f17653b016f3b40471818b2"
        rest = CCPRestSDK.REST(accountSid, accountToken, appId)
        captcha = Captcha.gene_text(number=4)
        result = rest.sendTemplateSMS(telephone, [captcha], "1")
        # rest.sendTemplateSMS(telephone, [captcha], "1")
        # return restful.success()


        if result:
            #如果发送成功,存储到缓存里面(服务器里面)
            zlcache.set(telephone,captcha)
            return restful.success()
        else:
            return restful.params_error(message='短信验证码发送失败 ')
    else:
        return restful.params_error(message='参数错误')




    # telephone=request.args.get('telephone')
    # if not telephone:
    #     return restful.params_error(message='请传入手机号码')
    # accountSid = "8a216da86f17653b016f3b4046b218ab"
    # accountToken = "ac156972012a43dab1782f1f89995ac9"
    # appId = "8a216da86f17653b016f3b40471818b2"
    # rest = CCPRestSDK.REST(accountSid, accountToken, appId)
    # #下面要有产生随机的验证码函数
    # captcha= Captcha.gene_text(number=4)
    # result = rest.sendTemplateSMS(telephone, [captcha], "1")
    # if result:
    #     return restful.success()
    # else:
    #     return restful.params_error(message='短信验证码发送失败')


#这里是后台代码
class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    #结合front/forms.py
    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())

##155课时(没有按照flask的来)，这里是测试代码
class SMSCodeView(views.MethodView):
    def get(self):
        #/smscode?tel=xxxxx
        telephone = request.args.get("tel")
        # telephone = request.values.get("tel")
        accountSid="8a216da86f17653b016f3b4046b218ab"
        accountToken = "ac156972012a43dab1782f1f89995ac9"
        appId ="8a216da86f17653b016f3b40471818b2"
        rest = CCPRestSDK.REST(accountSid,accountToken,appId)
        captcha = Captcha.gene_text(number=4)
        result = rest.sendTemplateSMS(telephone, [captcha], "1")
        # result= rest.sendTemplateSMS(telephone,["1234"],"1")
        print(result)
        return Response("success")



class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for("front.signup") and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    #post方法这里一般需要表单验证,这里代码在front/forms.py里面
    #这是登陆的后台代码
    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID]=user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return  restful.params_error(message='手机号或者密码错误')
        else:
            return restful.params_error(message=form.get_error())




bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

bp.add_url_rule('/smscode/',view_func=SMSCodeView.as_view('smscode'))

templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404页面</title>
</head>
<body>
您找的页面到火星去了~

</body>
</html>

templates/front/front_apost.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:500px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %} 学习论坛 {% endblock %}



{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
{% endblock %}


{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
            <!-- Indicators,指示器 -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>

            </ol>

            <!-- Wrapper for slides轮播图 -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                <a href="{{ banner.link_url }}">
                    <img src="{{ banner.image_url }}" alt="...">
                </a>
                </div>
                {% endfor %}

                {#    <div class="item active">#}
                {#        <a href="#">#}
                {#                  <img src="https://static-image.xfz.cn/1576747067_955.png" alt="...">#}
                {##}
                {#        </a>#}
                {#    </div>#}
                {#    <div class="item">#}
                {#         <a href="#">#}
                {#                  <img src="https://static-image.xfz.cn/1577338858_564.jpeg" alt="...">#}
                {##}
                {#        </a>#}
                {#      <div class="carousel-caption">#}
                {#        ...#}
                {#      </div>#}
                {#    </div>#}
                {#         <div class="item active">#}
                {#        <a href="#">#}
                {#                  <img src="https://img.alicdn.com/simba/img/TB14mh6qpP7gK0jSZFjSuw5aXXa.jpg" alt="...">#}
                {##}
                {#        </a>#}
                {#    </div>#}
                {#         <div class="item active">#}
                {#        <a href="#">#}
                {#                  <img src="https://img.alicdn.com/tps/i4/TB1u42drUT1gK0jSZFhSuuAtVXa.jpg_q90_.webp" alt="...">#}
                {##}
                {#        </a>#}
                {#    </div>#}

                </div>
                <!-- Controls 左右切换的按钮-->

                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="post-group">
                <ul class="post-group-head">
                    {% if current_sort == 1 %}
                        <li class="active"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                    {% else %}
                        <li ><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                    {% endif %}
                  {% if current_sort == 2 %}
                    <li class="active"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                    {% else %}
                    <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                    {% endif %}
                {% if current_sort == 3 %}
                    <li class="active"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                    {% else %}
                    <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                    {% endif %}
                 {% if current_sort == 4  %}
                    <li class="active"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                    {% else %}
                    <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                    {% endif %}

                </ul>
                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                {# 作者头像(自己上传or默认)#}
                                <img src="{{ post.author.avatar or url_for('static',filename='common/images/h.png') }}"
                                     alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    {#                                    {{ post.title }}#}
                                    <a href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a>
                                    {#                                 加精图标#}
                                    {% if post.highlight %}
                                        <span class="label label-danger">精华帖</span>
                                    {% endif %}
                                </p>
                                <p class="post-info">
                                    <span>作者:{{ post.author.username }}</span>
                                    <span>发表时间:{{ post.create_time }}</span>
                                    <span>评论:0</span>
                                    <span>阅读:0</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
                <div style="text-align: center">
                    {{ pagination.links }}

                </div>
            </div>

        </div>
        <div class="sm-container">
            <div style="padding-bottom:10px;">
                <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布帖子</a>
            </div>
            <div class="list-group">
                {% if current_board %}
                    <a href="/" class="list-group-item ">所有板块</a>
                {% else %}
                    <a href="/" class="list-group-item active">所有板块</a>
                {% endif %}
                {% for board in boards %}
                    {% if board.id== current_board %}
                        <a href="{{ url_for("front.index",bd=board.id) }}"
                           class="list-group-item active">{{ board.name }}</a>

                    {% else %}
                        <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}

                {% endfor %}

            </div>

        </div>
    </div>


{% endblock %}

templates/front/front_signbase.html
{% from 'common/_macros.html' import static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %} {% endblock %}</title>
     <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>

    <script src="{{ static('common/zlparam.js') }}"></script>
     <script src="{{ static("common/zlajax.js") }}"></script>

 <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">

    <script src="{{ static("common/sweetalert/sweetalert.min.js")}}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js")}}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css')}}">

    {% block  head %}

    {% endblock %}


</head>
<body>
<div class="outer-box">
<div class="logo-box">
    <a href="/">
        <img src="{{ static('common/images/h.png') }}" alt="">
    </a>
</div>
    <h2 class="page-title">
        {% block h2_block %}{% endblock %}
    </h2>
    <div class="sign-box">
{#        <div class="form-group">#}
{#           <div class="input-group">#}
{#                <input type="text" class="form-control"#}
{#            name="telephone" placeholder="手机号码">#}
{#               <span class="input-group-btn">#}
{#                   <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>#}
{#               </span>#}
{#           </div>#}
{##}
{#        </div>#}
{#         <div class="form-group">#}
{#        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">#}
{#     </div>#}
{#    <div class="form-group">#}
{#        <input type="text" class="form-control" name="username" placeholder="用户名">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <input type="password" class="form-control" name="password1" placeholder="密码">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <input type="password" class="form-control" name="password2" placeholder="确认密码">#}
{#    </div>#}
{##}
{##}
{#<div class="form-group">#}
{#        <div class="input-group">#}
{#            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">#}
{#            <span class="input-group-addon captcha-addon">#}
{#                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">#}
{#                <img id='captcha-img' class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">#}
{#            </span>#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <span style="display: none;"id="return-to-span">{{ return_to }}</span>#}
{#        <button  id="submit-btn"  class="btn btn-warning btn-block" id="submit-btn">立即注册</button>#}
{#    </div>#}

{% block signbox %}{% endblock %}

    </div>
        <span style="display: none;" id="return-to-span">{{ return_to }}</span>

</div>
</body>
</html>

templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}
{% from "common/_macros.html" import static %}

{% block title %}
    论坛登录
{% endblock %}

{% block head %}
    <script src="{{ static("front/js/front_signin.js") }}"></script>
{% endblock %}

{% block h2_block %}
    论坛账号登录
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住我
        </label>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
    </div>
    <div class="form-group">
        <a href="{{ url_for("front.signup") }}" class="signup-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
{#        <a href="#"></a>#}
    </div>
{% endblock %}

templates/front/front_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{{ url_for("front.signup") }}">注册</a>

</body>
</html>